# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.runs/synth_1/RV32I46F5SPSoCTOP.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.cache/wt [current_project]
set_property parent.project_path C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/itype.vh
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/branch.vh
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/alu_op.vh
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/load.vh
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/rtype.vh
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/store.vh
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/opcode.vh
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/csr.vh
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/alu_src_select.vh
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/rf_wd_select.vh
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/trap.vh
}
read_verilog -library xil_defaultlib {
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Button_Controller.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Debug_UART_Controller.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Byte_Enable_Logic.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Program_Counter.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Trap_Controller.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/PC_Controller.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/ID_EX_Register.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/PC_Plus_4.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Instruction_Memory.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Control_Unit.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/IF_ID_Register.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Instruction_Decoder.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Immediate_Generator.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Register_File_Debug.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/ALU.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Data_Memory.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/ALU_Controller.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Branch_Logic.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/MEM_WB_Register.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/CSR_File.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Exception_Detector.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/EX_MEM_Register.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Hazard_Unit.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Forward_Unit.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/Branch_Predictor.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/RV32I46F_5SP_Debug.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/UART_TX.v
  C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/sources_1/imports/Demo_sources/46F5SP_SoC_TOP.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/constrs_1/imports/Demo_sources/RV32I46F_5SP_Debug_XDC.xdc
set_property used_in_implementation false [get_files C:/Users/KHWL2025/RV32I46F5SP_Demo/RV32I46F5SP_Demo.srcs/constrs_1/imports/Demo_sources/RV32I46F_5SP_Debug_XDC.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top RV32I46F5SPSoCTOP -part xc7a200tsbg484-3
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RV32I46F5SPSoCTOP.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file RV32I46F5SPSoCTOP_utilization_synth.rpt -pb RV32I46F5SPSoCTOP_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
