# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.runs/synth_1/RV32I46F5SPMMIOSoCTOP.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.cache/wt [current_project]
set_property parent.project_path C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/alu_op.vh
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/rtype.vh
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/csr.vh
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/branch.vh
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/itype.vh
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/opcode.vh
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/load.vh
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/store.vh
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/alu_src_select.vh
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/rf_wd_select.vh
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/trap.vh
}
read_mem {
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/imports/basic_rv32s-31344d35dd9090e10fd692f257ae98d7bf7702a7/data_init.mem
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/imports/benchmark-dhrystone/dhrystone.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/ALU.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/ALU_Controller.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Branch_Logic.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Branch_Predictor.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Byte_Enable_Logic.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/CSR_File.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Control_Unit.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Data_Memory.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/EX_MEM_Register.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Exception_Detector.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Forward_Unit.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Hazard_Unit.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/ID_EX_Register.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/IF_ID_Register.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Immediate_Generator.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Instruction_Decoder.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Instruction_Memory.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/MEM_WB_Register.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/modules/MMIO_Interface.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/PC_Controller.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/PC_Plus_4.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Program_Counter.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/new/RV32I46F_5SP_MMIO.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/new/Register_File.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/Trap_Controller.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/UART_TX.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/new/Unified_UART_Controller.v
  C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/sources_1/imports/sources_1/imports/new/46F5SP_SoC_TOP.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/constrs_1/imports/new/RV32I46F_5SP_Debug_XDC.xdc
set_property used_in_implementation false [get_files C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/constrs_1/imports/new/RV32I46F_5SP_Debug_XDC.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/HyunWoo/Desktop/KHWL2025/RV32s_Dhry_Finale/RV32s_Dhry_Finale.srcs/utils_1/imports/synth_1/RV32I46F5SPMMIOSoCTOP.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top RV32I46F5SPMMIOSoCTOP -part xc7a200tsbg484-3
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RV32I46F5SPMMIOSoCTOP.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file RV32I46F5SPMMIOSoCTOP_utilization_synth.rpt -pb RV32I46F5SPMMIOSoCTOP_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
